/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content Info
         * @description Get metadata for a YouTube Music URL.
         *
         *     Returns title, artist, kind, track count, year, and thumbnail
         *     from a single API call without running the full extraction pipeline.
         */
        get: operations["get_content_info_api_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List all jobs (oldest first, FIFO order).
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new sync job.
         *
         *     Jobs are queued and executed sequentially. Returns 409 if queue is full.
         */
        post: operations["create_job_api_jobs_post"];
        /**
         * Clear Jobs
         * @description Clear all completed/failed/cancelled jobs.
         *
         *     Running and queued jobs are not affected.
         */
        delete: operations["clear_jobs_api_jobs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a running or queued job.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a completed, failed, or cancelled job.
         *
         *     Running or queued jobs cannot be deleted.
         */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resolve-orphans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Orphans
         * @description Resolve orphan file review and complete the job.
         */
        post: operations["resolve_orphans_api_jobs__job_id__resolve_orphans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job events via SSE
         * @description On connect, sends a snapshot event with all current jobs, then streams events as they occur. Heartbeat comments sent every 30s.
         */
        get: operations["stream_jobs_api_jobs_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get buffered log entries
         * @description Returns all currently buffered log entries as an array.
         */
        get: operations["get_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream log entries via SSE
         * @description On connect, sends all buffered log entries, then streams new entries as they arrive. Heartbeat comments sent every 30s.
         */
        get: operations["stream_logs_api_logs_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cookies/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cookies Status
         * @description Check if cookies file is configured.
         */
        get: operations["cookies_status_api_cookies_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cookies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cookies
         * @description Upload cookies.txt content (Netscape format).
         *
         *     The cookie file enables downloading from private playlists
         *     and accessing age-restricted content on YouTube Music.
         */
        post: operations["upload_cookies_api_cookies_post"];
        /**
         * Delete Cookies
         * @description Delete the cookies file.
         */
        delete: operations["delete_cookies_api_cookies_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drive/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drive Status
         * @description Get Google Drive configuration status.
         */
        get: operations["drive_status_api_drive_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drive/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Credentials
         * @description Upload OAuth2 client secrets JSON.
         */
        post: operations["upload_credentials_api_drive_credentials_post"];
        /**
         * Delete Credentials
         * @description Delete client secrets and token files.
         */
        delete: operations["delete_credentials_api_drive_credentials_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drive/auth/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Url
         * @description Generate Google OAuth2 authorization URL.
         */
        get: operations["get_auth_url_api_drive_auth_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drive/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Callback
         * @description Handle Google OAuth2 callback, exchange code for tokens.
         */
        get: operations["auth_callback_api_drive_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync All Subscriptions
         * @description Sync all enabled subscriptions.
         */
        post: operations["sync_all_subscriptions_api_subscriptions_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subscriptions
         * @description List all subscriptions.
         */
        get: operations["list_subscriptions_api_subscriptions_get"];
        put?: never;
        /**
         * Create Subscription
         * @description Create a new subscription.
         */
        post: operations["create_subscription_api_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Subscription
         * @description Delete a subscription.
         */
        delete: operations["delete_subscription_api_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Subscription
         * @description Update a subscription.
         */
        patch: operations["update_subscription_api_subscriptions__subscription_id__patch"];
        trace?: never;
    };
    "/api/subscriptions/{subscription_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Subscription
         * @description Sync a single subscription.
         */
        post: operations["sync_subscription_api_subscriptions__subscription_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduler Status
         * @description Get scheduler status (read-only).
         */
        get: operations["get_scheduler_status_api_scheduler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replaygain/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replaygain Status */
        get: operations["replaygain_status_api_replaygain_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replaygain/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Replaygain Scan */
        post: operations["start_replaygain_scan_api_replaygain_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replaygain/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Replaygain Scan */
        post: operations["cancel_replaygain_scan_api_replaygain_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Syncs
         * @description List sync history (newest first, paginated).
         */
        get: operations["list_syncs_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{sync_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Detail
         * @description Get a single sync with its track events.
         */
        get: operations["get_sync_detail_api_history__sync_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Track Events
         * @description List track events (filterable by event type, paginated).
         */
        get: operations["list_track_events_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Files
         * @description Upload and import local audio files.
         *
         *     Files are validated, saved to a temp directory, then processed
         *     as an import job with YTM metadata enrichment.
         */
        post: operations["import_files_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Liked Songs
         * @description List all liked songs from YouTube Music.
         */
        get: operations["list_liked_songs_api_likes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likes/thumbnails/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thumbnail
         * @description Serve a cached thumbnail, fetching from YouTube on first request.
         */
        get: operations["get_thumbnail_api_likes_thumbnails__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likes/{video_id}/unlike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlike Song
         * @description Remove a song from YouTube Music liked songs.
         */
        post: operations["unlike_song_api_likes__video_id__unlike_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likes/{video_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Song Files
         * @description Delete local and Drive files for a song.
         */
        post: operations["delete_song_files_api_likes__video_id__delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likes/{video_id}/redownload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redownload Song
         * @description Redownload a song by deleting local and Drive files and creating a new sync job.
         */
        post: operations["redownload_song_api_likes__video_id__redownload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioCodec
         * @description Supported audio output codecs.
         * @enum {string}
         */
        AudioCodec: "opus" | "mp3" | "m4a";
        /** Body_import_files_api_imports_post */
        Body_import_files_api_imports_post: {
            /** Files */
            files: string[];
        };
        /**
         * CancelJobResponse
         * @description Response when a job is cancelled.
         */
        CancelJobResponse: {
            /**
             * Message
             * @default Job cancelled
             * @constant
             */
            message: "Job cancelled";
        };
        /**
         * ClearJobsResponse
         * @description Response when jobs are cleared.
         */
        ClearJobsResponse: {
            /** Cleared */
            cleared: number;
        };
        /**
         * ContentInfo
         * @description Information about downloaded content (album, playlist, or track).
         */
        ContentInfo: {
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /**
             * Year
             * @default null
             */
            year: number | null;
            /**
             * Track Count
             * @default null
             */
            track_count: number | null;
            /**
             * Playlist Id
             * @default
             */
            playlist_id: string;
            /**
             * Url
             * Format: uri
             * @default null
             */
            url: string | null;
            /**
             * Thumbnail Url
             * Format: uri
             * @default null
             */
            thumbnail_url: string | null;
            /**
             * Audio Codec
             * @default null
             */
            audio_codec: string | null;
            /**
             * Audio Bitrate
             * @default null
             */
            audio_bitrate: number | null;
            /** @default playlist */
            kind: components["schemas"]["ContentKind"];
        };
        /**
         * ContentKind
         * @description Type of music content (album vs playlist vs track).
         * @enum {string}
         */
        ContentKind: "album" | "playlist" | "track";
        /**
         * CookiesStatusResponse
         * @description Cookies status response model.
         */
        CookiesStatusResponse: {
            /** Configured */
            configured: boolean;
        };
        /**
         * CookiesUploadRequest
         * @description Cookies upload request model.
         */
        CookiesUploadRequest: {
            /** Content */
            content: string;
        };
        /**
         * CookiesUploadResponse
         * @description Cookies upload response model.
         */
        CookiesUploadResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * CreateJobRequest
         * @description Request to create a new sync job.
         */
        CreateJobRequest: {
            /**
             * Url
             * Format: uri
             * @description YouTube or YouTube Music playlist, album, or single track URL
             * @example https://music.youtube.com/playlist?list=OLAK5uy_...
             * @example https://www.youtube.com/watch?v=VIDEO_ID
             */
            url: string;
            /**
             * Max Items
             * @description Maximum number of tracks to download
             */
            max_items?: number | null;
        };
        /** DeleteFilesResponse */
        DeleteFilesResponse: {
            /** Files Deleted */
            files_deleted: number;
            /** Drive Files Deleted */
            drive_files_deleted: number;
        };
        /**
         * DriveAuthUrlResponse
         * @description Drive OAuth2 authorization URL response.
         */
        DriveAuthUrlResponse: {
            /** Url */
            url: string;
        };
        /**
         * DriveCredentialsResponse
         * @description Drive credentials operation response.
         */
        DriveCredentialsResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * DriveCredentialsUploadRequest
         * @description Drive credentials upload request.
         */
        DriveCredentialsUploadRequest: {
            /** Content */
            content: string;
        };
        /**
         * DriveStatusResponse
         * @description Drive configuration status.
         */
        DriveStatusResponse: {
            /** Enabled */
            enabled: boolean;
            /** Has Client Secrets */
            has_client_secrets: boolean;
            /** Authorized */
            authorized: boolean;
            /** Folder Id */
            folder_id: string;
        };
        /**
         * ErrorResponse
         * @description Standard error response format.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response model.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "healthy";
        };
        /**
         * Job
         * @description A background sync job.
         */
        Job: {
            /** Id */
            id: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** @default opus */
            audio_format: components["schemas"]["AudioCodec"];
            /**
             * Max Items
             * @default null
             */
            max_items: number | null;
            /**
             * Subscription Id
             * @default null
             */
            subscription_id: string | null;
            /** @default manual */
            source: components["schemas"]["JobSource"];
            /** @default pending */
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** @default null */
            content_info: components["schemas"]["ContentInfo"] | null;
            /** @default null */
            download_stats: components["schemas"]["PhaseStats"] | null;
            /**
             * Pending Orphans
             * @default null
             */
            pending_orphans: components["schemas"]["OrphanFile"][] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
        };
        /**
         * JobCreatedResponse
         * @description Response when a job is created.
         */
        JobCreatedResponse: {
            /** Id */
            id: string;
            /**
             * Message
             * @default Job created
             * @constant
             */
            message: "Job created";
        };
        /**
         * JobSource
         * @description Source of a background job.
         * @enum {string}
         */
        JobSource: "manual" | "scheduler" | "import";
        /**
         * JobStatus
         * @description Status of a background job.
         * @enum {string}
         */
        JobStatus: "pending" | "fetching_info" | "downloading" | "importing" | "uploading" | "cleaning" | "awaiting_review" | "completed" | "failed" | "cancelled";
        /**
         * JobsResponse
         * @description Response for listing jobs.
         */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** LikedSong */
        LikedSong: {
            /** Video Id */
            video_id: string;
            /** Title */
            title: string;
            /** Artists */
            artists: string[];
            /** Album */
            album?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /** LikedSongsResponse */
        LikedSongsResponse: {
            /** Items */
            items: components["schemas"]["LikedSong"][];
            /** Total */
            total: number;
        };
        /**
         * LogEntry
         * @description Structured log entry sent to frontend via SSE.
         *
         *     Each log line from the backend is serialized as JSON using this schema.
         *     The frontend parses these entries and applies theme-aware styling.
         *
         *     The `entry_type` field enables discriminated union pattern matching
         *     in TypeScript for exhaustive type narrowing.
         * @example {
         *       "entry_type": "phase",
         *       "level": "INFO",
         *       "message": "Extracting metadata from playlist",
         *       "phase": "extracting",
         *       "phase_num": 1,
         *       "timestamp": "11:09:53"
         *     }
         * @example {
         *       "current": 1,
         *       "entry_type": "progress",
         *       "event_type": "track_download",
         *       "level": "INFO",
         *       "message": "Queen - Bohemian Rhapsody",
         *       "timestamp": "11:09:54",
         *       "total": 10,
         *       "track_artist": "Queen",
         *       "track_title": "Bohemian Rhapsody"
         *     }
         * @example {
         *       "entry_type": "stats",
         *       "level": "INFO",
         *       "message": "Downloads complete",
         *       "stats": {
         *         "failed": 0,
         *         "skipped_by_reason": {
         *           "file_exists": 2
         *         },
         *         "stats_type": "download",
         *         "success": 8
         *       },
         *       "timestamp": "11:09:55"
         *     }
         */
        LogEntry: {
            /**
             * Entry Type
             * @description Entry type for discriminated union matching
             * @default default
             * @enum {string}
             */
            entry_type: "header" | "phase" | "stats" | "progress" | "status" | "file" | "default";
            /**
             * Timestamp
             * @description Log timestamp in HH:MM:SS format
             */
            timestamp: string;
            /**
             * Level
             * @description Log level: DEBUG, INFO, WARNING, ERROR
             */
            level: string;
            /**
             * Message
             * @description Human-readable log message
             */
            message: string;
            /**
             * Phase
             * @description Current operation phase
             * @default null
             */
            phase: ("extracting" | "downloading" | "composing" | "normalizing" | "uploading" | "scanning" | "cleaning") | null;
            /**
             * Phase Num
             * @description Phase number (1-6)
             * @default null
             */
            phase_num: number | null;
            /**
             * Event Type
             * @description Specific event type for granular tracking
             * @default null
             */
            event_type: ("track_download" | "file_upload" | "file_cleanup") | null;
            /**
             * Current
             * @description Current item index in progress (0-indexed)
             * @default null
             */
            current: number | null;
            /**
             * Total
             * @description Total number of items to process
             * @default null
             */
            total: number | null;
            /**
             * Status
             * @description Operation result status
             * @default null
             */
            status: ("success" | "skipped" | "failed") | null;
            /**
             * @description Aggregate statistics for batch operations
             * @default null
             */
            stats: components["schemas"]["LogStats"] | null;
            /**
             * File Path
             * @description Path to generated or downloaded file
             * @default null
             */
            file_path: string | null;
            /**
             * File Type
             * @description Type of file: m3u, cover, audio
             * @default null
             */
            file_type: ("m3u" | "cover" | "audio") | null;
            /**
             * Track Title
             * @description Track title being processed
             * @default null
             */
            track_title: string | null;
            /**
             * Track Artist
             * @description Track artist name
             * @default null
             */
            track_artist: string | null;
            /**
             * Header
             * @description Section header text for visual separation
             * @default null
             */
            header: string | null;
        };
        /**
         * LogStats
         * @description Statistics for batch operations.
         *
         *     Uses a discriminator field (stats_type) for frontend type narrowing,
         *     and dictionary-based skip reason counts for scalability.
         *
         *     Attributes:
         *         stats_type: Discriminator indicating extraction or download stats.
         *         success: Number of successful operations.
         *         failed: Number of failed operations.
         *         skipped_by_reason: Count of skipped items by reason.
         */
        LogStats: {
            /**
             * Stats Type
             * @description Type of stats: extraction, download, upload, or replaygain
             * @enum {string}
             */
            stats_type: "extraction" | "download" | "upload" | "replaygain" | "cleanup";
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Cached
             * @default 0
             */
            cached: number;
            /**
             * Unmatched
             * @default 0
             */
            unmatched: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Cleaned
             * @default 0
             */
            cleaned: number;
            /**
             * Skipped By Reason
             * @description Count of skipped items by reason
             */
            skipped_by_reason?: {
                [key: string]: number;
            };
        };
        /**
         * OrphanDecision
         * @description Decision for a single orphan file.
         */
        OrphanDecision: {
            /** Path */
            path: string;
            /**
             * Action
             * @enum {string}
             */
            action: "delete" | "keep" | "never_delete";
        };
        /**
         * OrphanFile
         * @description An orphaned file found during cleanup.
         */
        OrphanFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /**
         * PhaseStats
         * @description Statistics for a processing phase (extraction or download).
         *
         *     Uses dictionary-based skip reason counts for scalability.
         *     Adding new skip reasons only requires updating the SkipReason enum.
         *
         *     Attributes:
         *         success: Number of successfully processed items.
         *         failed: Number of failed items.
         *         skipped_by_reason: Count of skipped items by reason.
         *
         *     Example:
         *         >>> stats = PhaseStats(
         *         ...     success=8,
         *         ...     failed=1,
         *         ...     skipped_by_reason={SkipReason.FILE_EXISTS: 2}
         *         ... )
         *         >>> stats.skipped  # 2
         *         >>> stats.total    # 11
         *         >>> stats.success_rate  # 72.7...
         */
        PhaseStats: {
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Skipped By Reason */
            skipped_by_reason?: {
                [key: string]: number;
            };
        };
        /** RedownloadResponse */
        RedownloadResponse: {
            /** Job Id */
            job_id: string;
        };
        /** ReplayGainScanResponse */
        ReplayGainScanResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "cancelled";
        };
        /** ReplayGainStatusResponse */
        ReplayGainStatusResponse: {
            /** Available */
            available: boolean;
            /** Running */
            running: boolean;
            /** Progress */
            progress?: number | null;
            /** Current Directory */
            current_directory?: string | null;
        };
        /**
         * ResolveOrphansRequest
         * @description Request to resolve orphan review.
         */
        ResolveOrphansRequest: {
            /** Decisions */
            decisions: components["schemas"]["OrphanDecision"][];
        };
        /**
         * ResolveOrphansResponse
         * @description Response when orphans are resolved.
         */
        ResolveOrphansResponse: {
            /**
             * Message
             * @default Orphans resolved
             * @constant
             */
            message: "Orphans resolved";
        };
        /**
         * SchedulerStatus
         * @description Scheduler status response.
         */
        SchedulerStatus: {
            /** Running */
            running: boolean;
            /** Enabled */
            enabled: boolean;
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            /** Next Run At */
            next_run_at: string | null;
            subscription_counts: components["schemas"]["SubscriptionCounts"];
        };
        /**
         * SkipReason
         * @description Reason why a track was skipped.
         *
         *     Used in both extraction and download phases:
         *     - Extraction: UNSUPPORTED_VIDEO_TYPE, NO_VIDEO_ID, REGION_UNAVAILABLE
         *     - Download: FILE_EXISTS
         * @enum {string}
         */
        SkipReason: "file_exists" | "unsupported_video_type" | "ugc" | "no_video_id" | "region_unavailable";
        /**
         * SubscriptionCounts
         * @description Subscription count statistics.
         */
        SubscriptionCounts: {
            /** Total */
            total: number;
            /** Enabled */
            enabled: number;
        };
        /**
         * SubscriptionCreate
         * @description Request to create a subscription.
         */
        SubscriptionCreate: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Max Items */
            max_items?: number | null;
        };
        /**
         * SubscriptionListResponse
         * @description List of subscriptions response.
         */
        SubscriptionListResponse: {
            /** Items */
            items: components["schemas"]["SubscriptionResponse"][];
        };
        /**
         * SubscriptionResponse
         * @description Subscription response.
         */
        SubscriptionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["SubscriptionType"];
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Max Items */
            max_items: number | null;
            /**
             * Thumbnail Url
             * Format: uri
             */
            thumbnail_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /**
         * SubscriptionType
         * @description Type of content subscription.
         * @enum {string}
         */
        SubscriptionType: "playlist";
        /**
         * SubscriptionUpdate
         * @description Request to update a subscription.
         */
        SubscriptionUpdate: {
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SyncDetailResponse
         * @description Single sync with its track events.
         */
        SyncDetailResponse: {
            sync: components["schemas"]["SyncHistoryResponse"];
            /** Track Events */
            track_events: components["schemas"]["TrackEventResponse"][];
        };
        /**
         * SyncHistoryResponse
         * @description A sync history record.
         */
        SyncHistoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Track Count */
            track_count: number | null;
            /** Tracks Added */
            tracks_added: number;
            /** Tracks Failed */
            tracks_failed: number;
            /** Tracks Skipped */
            tracks_skipped: number;
            /** Orphans Deleted */
            orphans_deleted: number;
            /** Orphans Kept */
            orphans_kept: number;
            /** Audio Codec */
            audio_codec: string | null;
            /** Audio Bitrate */
            audio_bitrate: number | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SyncListResponse
         * @description Paginated list of sync history.
         */
        SyncListResponse: {
            /** Items */
            items: components["schemas"]["SyncHistoryResponse"][];
            /** Total */
            total: number;
        };
        /**
         * SyncResponse
         * @description Response for sync operations.
         */
        SyncResponse: {
            /** Job Ids */
            job_ids: string[];
        };
        /**
         * TrackEventListResponse
         * @description Paginated list of track events.
         */
        TrackEventListResponse: {
            /** Items */
            items: components["schemas"]["TrackEventResponse"][];
            /** Total */
            total: number;
        };
        /**
         * TrackEventResponse
         * @description A track event record.
         */
        TrackEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sync Id */
            sync_id: string | null;
            /** Event */
            event: string;
            /** Path */
            path: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UnlikeResponse */
        UnlikeResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * SnapshotEvent
         * @description Initial snapshot of all jobs sent on SSE connection.
         */
        SnapshotEvent: {
            /**
             * Type
             * @default snapshot
             * @constant
             */
            type: "snapshot";
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /**
         * CreatedEvent
         * @description Emitted when a new job is created.
         */
        CreatedEvent: {
            /**
             * Type
             * @default created
             * @constant
             */
            type: "created";
            job: components["schemas"]["Job"];
        };
        /**
         * UpdatedEvent
         * @description Emitted when a job's status or progress changes.
         */
        UpdatedEvent: {
            /**
             * Type
             * @default updated
             * @constant
             */
            type: "updated";
            job: components["schemas"]["Job"];
        };
        /**
         * DeletedEvent
         * @description Emitted when a job is deleted.
         */
        DeletedEvent: {
            /**
             * Type
             * @default deleted
             * @constant
             */
            type: "deleted";
            /** Jobid */
            jobId: string;
        };
        /**
         * ClearedEvent
         * @description Emitted when finished jobs are cleared.
         */
        ClearedEvent: {
            /**
             * Type
             * @default cleared
             * @constant
             */
            type: "cleared";
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_content_info_api_info_get: {
        parameters: {
            query: {
                /** @description YouTube Music URL (playlist, album, or track) */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Queue is full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_jobs_api_jobs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearJobsResponse"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelJobResponse"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot delete running job */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_orphans_api_jobs__job_id__resolve_orphans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveOrphansRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveOrphansResponse"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job not awaiting review */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_jobs_api_jobs_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SnapshotEvent"] | components["schemas"]["CreatedEvent"] | components["schemas"]["UpdatedEvent"] | components["schemas"]["DeletedEvent"] | components["schemas"]["ClearedEvent"];
                };
            };
        };
    };
    get_logs_api_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
        };
    };
    stream_logs_api_logs_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LogEntry"];
                };
            };
        };
    };
    cookies_status_api_cookies_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesStatusResponse"];
                };
            };
        };
    };
    upload_cookies_api_cookies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookiesUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cookies_api_cookies_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesUploadResponse"];
                };
            };
        };
    };
    drive_status_api_drive_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveStatusResponse"];
                };
            };
        };
    };
    upload_credentials_api_drive_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriveCredentialsUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveCredentialsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credentials_api_drive_credentials_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveCredentialsResponse"];
                };
            };
        };
    };
    get_auth_url_api_drive_auth_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveAuthUrlResponse"];
                };
            };
        };
    };
    auth_callback_api_drive_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_all_subscriptions_api_subscriptions_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    list_subscriptions_api_subscriptions_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
                type?: components["schemas"]["SubscriptionType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_api_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_api_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subscription_api_subscriptions__subscription_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_subscription_api_subscriptions__subscription_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduler_status_api_scheduler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatus"];
                };
            };
        };
    };
    replaygain_status_api_replaygain_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayGainStatusResponse"];
                };
            };
        };
    };
    start_replaygain_scan_api_replaygain_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayGainScanResponse"];
                };
            };
        };
    };
    cancel_replaygain_scan_api_replaygain_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayGainScanResponse"];
                };
            };
        };
    };
    list_syncs_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_detail_api_history__sync_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_track_events_api_tracks_get: {
        parameters: {
            query?: {
                event?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_files_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_files_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Invalid file upload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Queue is full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_liked_songs_api_likes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikedSongsResponse"];
                };
            };
        };
    };
    get_thumbnail_api_likes_thumbnails__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlike_song_api_likes__video_id__unlike_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlikeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_song_files_api_likes__video_id__delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redownload_song_api_likes__video_id__redownload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
